#!/usr/bin/env ruby

require "kalah"

game = Kalah::Kalah.new

while not game.has_current_player_won do
  puts game # Print game status
  puts "Current player: #{game.current_player}"
  puts "From which house do you want to sow?"
  begin
    game.sow gets.to_i # Sow house.
  rescue Kalah::IllegalMoveError => e
    puts e
  end
end

puts "#{game.current_player} has won the game"
